version: '3.7'

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: app

    api:
        build:
            context: .
        depends_on:
          - mysql
        ports:
          - 8080:80
        volumes:
          - ./docker/startup.sh:/entrypoint.d/startup.sh
          - ./docker/nginx/location-root.conf:/opt/docker/etc/nginx/vhost.common.d/10-location-root.conf
          - ./docker/nginx/php.conf:/opt/docker/etc/nginx/vhost.common.d/10-php.conf
        environment:
            DB_DRIVER: pdo_mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD:
            DB_NAME: app
